seed: 42

# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: MultivariateGaussianMixin # GaussianMixin
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.8
    network:
      - name: net
        input: STATES
        layers:  [256, 64, 64] #[256, 128, 64]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [256, 64, 64] #[256, 128, 64]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# PPO agent configuration (field names are from RPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/Rpo.html
agent:
  class: RPO
  rollouts: 30
  learning_epochs: 10
  mini_batches: 1 # 20 * NUM_ENVS / 1024  # horizon_length * num_actors / minibatch_size

  alpha: 0.5
  discount_factor: 0.99
  lambda: 0.98

  learning_rate: 1.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
    min_lr: 1.0e-5

  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null

  random_timesteps: 0
  learning_starts: 0

  grad_norm_clip: 0.5
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True

  entropy_loss_scale: 0.01
  value_loss_scale: 2.0

  kl_threshold: 0.0

  rewards_shaper_scale: 0.01
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "iiwa_lift"
    experiment_name: "oracle_info"
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 30000
  environment_info: log
